# UI Angular
ui:
  build: ./docker/dev/run/frontend
  #image: httpd:2.4.17
  labels:
    com.mgreau.tennistour.ui: "UI"
  ports:
    - "8888:80"
  volumes:
    - ./app/tennistour-ui/app:/usr/local/apache2/htdocs/
  environment:
    - WEBSOCKET_HOST=docker4devtennistourapp_ws_run
  links:
    - ws_run
    #- ws_run:ws-tennistour

# Backend:: Batch App
batch_run:
  build: ./docker/dev/run/backend
  labels:
    com.mgreau.tennistour.batch.run: "Batch Binaries"
  ports:
    - "7777:8080"
  volumes:
    - ./app/tennistour-batch/target/batch:/opt/jboss/wildfly/standalone/deployments/ROOT.war/
  links:
      - db
      - cache:redis-cache

# Backend:: Run WebSocket
ws_run:
  build: ./docker/dev/run/backend
  labels:
    com.mgreau.tennistour.ws.run: "WS Binaries"
  expose:
    - "8080"
  volumes:
    - ./app/tennistour-realtime-server/target/ws:/opt/jboss/wildfly/standalone/deployments/ROOT.war/
  links:
      - db
      - cache:redis-cache

cache:
  image: redis

dbdata:
  image: mysql:5.7
  volumes:
    - /var/lib/mysql

db:
  image: mysql:5.7
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=tennistour
    - MYSQL_DATABASE=tennistour
    - MYSQL_USER=tennistour
    - MYSQL_PASSWORD=tennistour
