# Backend:: Batch App
batch_run:
  build: ./docker/dev/run/backend
  labels:
    com.mgreau.tennistour.batch.run: "Batch Binaries"
  ports:
    - "7777:8080"
    - "8787:8787"
  #debug
  command: ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "--debug", "8787"]
  expose:
    - "8787"
  volumes:
    - ./app/tennistour-batch/target/batch:/opt/jboss/wildfly/standalone/deployments/ROOT.war/
  links:
      - db

dbdata:
  image: mysql:5.7
  volumes:
    - /var/lib/mysql

db:
  image: mysql:5.7
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=tennistour
    - MYSQL_DATABASE=tennistour
    - MYSQL_USER=tennistour
    - MYSQL_PASSWORD=tennistour
